### ISSUE TITLE
Add error bars on summary plot.

### ISSUE THREAD

**Issue by Shimuuar** [bos/criterion#6] opened 2012-01-01 17:29 UTC
It would be nice to have error bars on summary plots so one could easily see whether difference could be explained by statistical fluctuations. Sadly flot lack builtin error bars but there is a plugin for it. Another possible approach is to use overlapping bar plots a la:

```
-----------
   |  |   |
-----------
```

**Comment by jberryman** [comment] 2015-01-08 21:32
I've been thinking what I really want in the overview is a squished down version of the contour plot showing the distribution of samples and mean. In my experience this would be more useful in situations where there is significant deviation, since e.g. it would communicate clearly if there are two distinct clusters, etc. 

It's awesome there's a PR for adding error bars though, maybe what I want could be a new feature request and an alternate view that could be toggled.

**Comment by rrnewton** [comment] 2016-08-16 14:16
Are people happy with the fact that the bars show the *mean* rather than the OLS regression?  We often use criterion in scenarios where these are vastly different.

Also, the html reports don't even show the other (non-time) regressions, even in the textual output.

**Comment by RyanGlScott** [comment] 2017-12-06 19:26
Fixed in #150.

**Closed by RyanGlScott** 2017-12-06 19:26 UTC
Labels: Enhancement
