### ISSUE TITLE
`index out of bounds` and `thread blocked indefinitely` runtime errors.

### ISSUE THREAD

**Issue by kindaro** [bos/criterion#162] opened 2017-10-06 06:56 UTC
While investigating [issue 161](https://github.com/bos/criterion/issues/161), I made some more test runs and discovered, unfortunately, another runtime error (to be exact, two in a row), also transient by nature.

Pathological output:

    benchmarking const
    time                 56.16 ns   (56.10 ns .. 56.21 ns)
                         1.000 R²   (1.000 R² .. 1.000 R²)

Error text:

    CriterionRight.hs: ./Data/Vector/Generic.hs:245 ((!)): index out of bounds
    (-9223372036854775808,1000)
    CallStack (from HasCallStack):
      error, called at ./Data/Vector/Internal/Check.hs:87:5 in
    vector-0.12.0.1-CnPH69pDwM4A5esizlXfXi:Data.Vector.Internal.Check
    CriterionRight.hs: thread blocked indefinitely in an MVar operation

These were collected via a simplistic automation script, so I cannot tell exactly how the error and the output should be interleaved. What I can tell is that an error of such pattern happened 36 times during 100 runs.

I'm attaching the log generated by my automation script. The automation script itself [can be reviewed in the repository](https://github.com/kindaro/criterion-wut/blob/master/RepeatedlyTest.hs) and the measures replicated by the kind reader.

[RepeatedlyTest.hs.log](https://github.com/bos/criterion/files/1361757/RepeatedlyTest.hs.log)

**Comment by RyanGlScott** [comment] 2017-10-06 15:14
I can't reproduce this, so I would appreciate debugging help from anyone who can.

**Comment by sharkdp** [comment] 2018-01-16 19:14
I think I stumbled upon the same bug here: https://github.com/Gabriel439/bench/issues/21

**Comment by RyanGlScott** [comment] 2018-01-18 17:11
This should be fixed after we merged #178. @kindaro, can you verify if the issue still persists with `criterion` HEAD?

I'll optimistically close this issue, since @patrickdoc reports not being able to reproduce it anymore, but feel free to re-open if that is not the case.

**Closed by RyanGlScott** 2018-01-18 17:11 UTC
Labels: Bug, Help wanted
