### ISSUE TITLE
Constant function has severely inflated variance.

### ISSUE THREAD

**Issue by kindaro** [bos/criterion#160] opened 2017-10-05 21:14 UTC
I mean, `-9223372036854775808%` *does* look inflated.

    % ./CriterionRight.hs
    benchmarking const
    time                 56.50 ns   (56.29 ns .. 56.87 ns)
                         1.000 R²   (1.000 R² .. 1.000 R²)
    mean                 27.17 ns   (27.17 ns .. 27.17 ns)
    std dev              0.0 s      (0.0 s .. 0.0 s)
    variance introduced by outliers: -9223372036854775808% (severely inflated)

The code for the benchmark is indeed simple:

    unrelatedBenchmark n = bench "const" $ nf (const 23 :: Int -> Int) 29

The kind reader may review the code and see for themselves [here](github.com/kindaro/criterion-wut).

**Comment by RyanGlScott** [comment] 2017-10-06 00:16
Yikes! You're seeing that because `criterion` is almost assuredly dividing by 0 due to the fact that the range of the `std dev` is, well, 0!

That being said, I can't reproduce the issue on my machine. What version of `criterion` are you using? How/with what flags are you compiling and running it? Does this issue occur on every run, or does it only happen once in a while?

**Comment by kindaro** [comment] 2017-10-06 07:17
@RyanGlScott I used the most recent version to be found in `stackage`'s nightly snapshot to the date. I run the code as a `stack` script with no additional compiler flags. You can review the code [in the repository](https://github.com/kindaro/criterion-wut/blob/1730db83ace14a33d1e4fe3df5f4729524404a18/CriterionRight.hs). The system is a Celeron 1.80GHz, running Arch Linux with kernel 4.9.

I believe the numbers are the same every run, or at least the majority of runs.

**Comment by RyanGlScott** [comment] 2017-10-06 15:13
For the sake of posterity: this `stack` script is using `criterion-1.2.2.0`.

Unfortunately, I am completely unable to reproduce this, so help would be appreciated from anyone who experiences this issue.

**Comment by RyanGlScott** [comment] 2018-01-18 17:10
This should be fixed after we merged #178. @kindaro, can you verify if the issue still persists with `criterion` HEAD?

I'll optimistically close this issue, since @patrickdoc reports not being able to reproduce it anymore, but feel free to re-open if that is not the case.

**Closed by RyanGlScott** 2018-01-18 17:10 UTC
Labels: Bug, Help wanted
