### ISSUE TITLE
HTML statistics different from console ones

### ISSUE THREAD

**Issue by enolan** [bos/criterion#153] opened 2017-08-04 17:30 UTC
I'm seeing very different confidence intervals on the HTML report than on the command line. In one benchmark I see a confidence interval of 340 ns - 460 ns with a mean of 169 us in the report and 168.6 us - 169.4 us with a mean of 168.9 us. The code I'm benchmarking is proprietary, but with some guidance I can try to boil down a test case. This is Criterion version 1.2.1.0 with GHC 8.2.1 and Stackage nightly-2017-07-31. Console output and report in [this gist](https://gist.github.com/enolan/ba2f66ba128689ad136815be393924fc).

**Comment by RyanGlScott** [comment] 2017-08-04 21:20
Oh dear, this looks really bad.

From some quick testing, it appears that this is a regression that occurred sometime between `criterion-1.1.4.0` (which doesn't seem to have this problem) and `criterion-1.2.0.0` (which does). I'll try to see if any particular commits look suspicious.

**Comment by RyanGlScott** [comment] 2017-08-04 22:02
After a quick investigation, it appears that #141 is where everything went wrong (I tested commit 36c22078b704f3c99dd16c9332f3fc78ab650d17, before #141 landed, and it works fine). To make things worse, I can't pinpoint an exact commit since not all of the commits in the PR still build, but several large changes came about from that:

* In 97540e8709ce4904550f5078e940972bb94c11b5, we migrated over from `statistics-0.13` to `0.14`. That commit doesn't built, but abe1760c1dc03bf67747e5fb9009a083aca660c2, which is some number of commits later, does. When I test abe1760c1dc03bf67747e5fb9009a083aca660c2, I get HTML reports where every single lower and upper bound is `xxx`, which is certainly not a good sign. My guess is that `statistics-0.14` changed its `ToJSON` instances, which causes the HTML report to go haywire.
* In df4515c4ba62d444b803d1e80e0f8f96eb4a8d31, we migrated from `hastache` to `microstache`. That commit is mostly routine API conversion, but there is a noticeable change in behavior, starting at https://github.com/bos/criterion/commit/df4515c4ba62d444b803d1e80e0f8f96eb4a8d31#diff-ca0bc1a3409ff865bbb3161972350affL76 : the HTML report now uses, e.g., `estError.confIntLDX` instead of `estLowerBound`. This causes the HTML reports to give actual numbers again for the lower and upper bounds, but I'm guessing these aren't the numbers we really want (cc'ing @phadej in case he has any insight here).

**Comment by RyanGlScott** [comment] 2017-08-04 22:15
Ack, I know what is happening here. The issue is that we're not computing the lower/upper version bounds properly in the HTML report--instead, we're just retrieving the confidence intervals! We should be subtracting and adding these intervals from the point estimate to get the actual lower and upper bound, as done in the [`confidenceInterval`](http://hackage.haskell.org/package/statistics-0.14.0.2/docs/src/Statistics-Types.html#confidenceInterval) function in `statistics-0.14`.

Now I'm paranoid that we're doing //other// things incorrectly in the HTML report post-`statistics-0.14`, so I'll do an audit of that file and submit a PR to make things right again.

**Comment by RyanGlScott** [comment] 2017-08-04 22:57
Ugh. To make things worse, it's not just `templates/default.tpl` that's affected - it affects `www/report.html` and `www/fibber.html`, since they're also retrieving lower/upper bounds incorrectly post-`statistics-0.14`.

**Comment by RyanGlScott** [comment] 2017-08-04 23:35
Never mind, I suppose we needn't touch anything in the `www/` directory, since it's just showing a sample `criterion` report. Moreover, it's showing a report from well before #141, so it should still be working.

**Closed** 2017-08-05 15:55 UTC
Labels: Bug, High priority

**Comment by RyanGlScott** [comment] 2017-08-05 16:37
I've released [`criterion-1.2.2.0`](http://hackage.haskell.org/package/criterion-1.2.2.0) with this bugfix, and deprecated versions 1.2.0.0 and 1.2.1.0 (in which the bug was present).

**Comment by enolan** [comment] 2017-08-05 21:03
Thanks a lot guys!
